"""Tests for `<browser> export` -- the unified one-file dump command.

`export` collects user-customized state from the live profile and the
managed-policy file into a single TOML document that is round-trip
compatible with `apply`.  It deliberately omits `[settings]` because
Chromium does not expose a defaults table for arbitrary prefs.

The tests exercise the in-process command functions directly (no
subprocess) so we can monkeypatch the per-browser `pwa.POLICY_FILE`
and friends -- the same fixture pattern as `test_pwa_apply.py`.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import pytest

if sys.version_info >= (3, 11):
    import tomllib
else:
    import tomli as tomllib  # type: ignore[no-redef]

from dotbrowser import brave as brave_pkg
from dotbrowser import chrome as chrome_pkg
from dotbrowser import edge as edge_pkg
from dotbrowser import vivaldi as vivaldi_pkg
from dotbrowser.brave import pwa as brave_pwa
from dotbrowser.chrome import pwa as chrome_pwa
from dotbrowser.edge import pwa as edge_pwa
from dotbrowser.vivaldi import pwa as vivaldi_pwa


# ---------------------------------------------------------------------------
# Helpers: redirect each browser's pwa policy reader to a tmp JSON file so
# tests can seed force-installed PWAs without touching the real OS.
# ---------------------------------------------------------------------------

def _redirect_pwa(monkeypatch: pytest.MonkeyPatch, pwa_module, fake_path: Path) -> None:
    """Redirect a browser's pwa module to read from `fake_path`.

    Mirrors test_pwa_apply.py's strategy.  We don't write here -- export
    only reads -- so we just override the read chain.  On Linux/macOS
    the read goes through ``_read_existing_payload`` which reads
    ``POLICY_FILE``; on Windows it goes through the same wrapper but
    ultimately hits the registry.  Stubbing ``_read_existing_payload``
    works for both.
    """
    def fake_read_payload() -> dict:
        if not fake_path.exists():
            return {}
        try:
            return json.loads(fake_path.read_text())
        except (json.JSONDecodeError, OSError):
            return {}

    monkeypatch.setattr(pwa_module, "_read_existing_payload", fake_read_payload)
    if sys.platform != "win32":
        # build_dump_block also formats POLICY_FILE into the "no PWAs"
        # comment, so point it at the fake location for cosmetic accuracy.
        monkeypatch.setattr(pwa_module, "POLICY_FILE", fake_path)


def _seed_policy(fake_path: Path, urls: list[str]) -> None:
    fake_path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "WebAppInstallForceList": [
            {"url": u, "default_launch_container": "window",
             "create_desktop_shortcut": True}
            for u in urls
        ]
    }
    fake_path.write_text(json.dumps(payload))


# ---------------------------------------------------------------------------
# Brave -- shortcuts (diff vs default) + pwa
# ---------------------------------------------------------------------------

def test_brave_export_includes_diff_shortcuts_and_pwa(
    fake_profile_root: Path,
    tmp_path: Path,
    capsys: pytest.CaptureFixture,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Brave export emits [shortcuts] (only entries that differ from the
    profile's `brave.default_accelerators`) plus [pwa] reflecting the
    current managed-policy file."""
    fake_policy = tmp_path / "policy" / "dotbrowser-pwa.json"
    _redirect_pwa(monkeypatch, brave_pwa, fake_policy)
    _seed_policy(fake_policy, ["https://squoosh.app/"])

    args = argparse.Namespace(
        profile_root=fake_profile_root,
        profile="Default",
        output=None,
        all_shortcuts=False,
        channel="stable",
    )
    brave_pkg.cmd_export(args)
    out = capsys.readouterr().out

    # Header line always present.
    assert "Generated by `dotbrowser brave export`" in out
    # Header explains why settings is missing.
    assert "[settings] is intentionally NOT exported" in out

    # Output parses as TOML.
    doc = tomllib.loads(out)

    # focus_location was overridden in the fixture; new_tab matches default
    # and should be filtered out.
    assert "shortcuts" in doc
    assert doc["shortcuts"] == {"focus_location": ["Alt+KeyL"]}

    # PWA list reflects the seeded policy.
    assert doc["pwa"]["urls"] == ["https://squoosh.app/"]


def test_brave_export_all_shortcuts_includes_defaults(
    fake_profile_root: Path,
    tmp_path: Path,
    capsys: pytest.CaptureFixture,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """--all-shortcuts removes the diff filter and emits every binding."""
    fake_policy = tmp_path / "policy" / "dotbrowser-pwa.json"
    _redirect_pwa(monkeypatch, brave_pwa, fake_policy)

    args = argparse.Namespace(
        profile_root=fake_profile_root,
        profile="Default",
        output=None,
        all_shortcuts=True,
        channel="stable",
    )
    brave_pkg.cmd_export(args)
    out = capsys.readouterr().out

    doc = tomllib.loads(out)
    # Both the user-customized one AND the at-default one are present.
    assert set(doc["shortcuts"]) == {"focus_location", "new_tab"}


def test_brave_export_writes_to_file(
    fake_profile_root: Path,
    tmp_path: Path,
    capsys: pytest.CaptureFixture,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """-o writes to the given file, prints `wrote <path>`, stdout has no TOML."""
    fake_policy = tmp_path / "policy" / "dotbrowser-pwa.json"
    _redirect_pwa(monkeypatch, brave_pwa, fake_policy)

    dest = tmp_path / "exported.toml"
    args = argparse.Namespace(
        profile_root=fake_profile_root,
        profile="Default",
        output=str(dest),
        all_shortcuts=False,
        channel="stable",
    )
    brave_pkg.cmd_export(args)

    captured = capsys.readouterr().out
    assert f"wrote {dest}" in captured
    assert "[shortcuts]" not in captured  # body went to file, not stdout

    body = dest.read_text(encoding="utf-8")
    doc = tomllib.loads(body)
    assert "shortcuts" in doc
    assert "pwa" in doc


def test_brave_export_round_trips_through_apply(
    fake_profile_root: Path,
    tmp_path: Path,
    capsys: pytest.CaptureFixture,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Export -> parse TOML -> feed to apply and verify it's a no-op for
    [shortcuts] (since the values are what's already in Preferences)."""
    fake_policy = tmp_path / "policy" / "dotbrowser-pwa.json"
    _redirect_pwa(monkeypatch, brave_pwa, fake_policy)

    args = argparse.Namespace(
        profile_root=fake_profile_root,
        profile="Default",
        output=None,
        all_shortcuts=False,
        channel="stable",
    )
    brave_pkg.cmd_export(args)
    out = capsys.readouterr().out
    doc = tomllib.loads(out)

    # Parsed shortcuts table can be fed directly into plan_apply.
    from dotbrowser.brave import shortcuts as brave_shortcuts
    from dotbrowser._base.utils import find_preferences, load_prefs
    prefs_path = find_preferences(fake_profile_root, "Default")
    plan = brave_shortcuts.plan_apply(prefs_path, load_prefs(prefs_path), doc["shortcuts"])
    # No diff means apply would be a no-op for shortcuts.
    assert plan.empty


# ---------------------------------------------------------------------------
# Edge / Chrome -- pwa-only (no shortcuts)
# ---------------------------------------------------------------------------

def _make_minimal_profile(tmp_path: Path) -> Path:
    """Create a Default profile with a minimal Preferences for browsers
    that don't need shortcut/setting fixtures (Edge/Chrome export)."""
    profile = tmp_path / "Default"
    profile.mkdir()
    (profile / "Preferences").write_text(json.dumps({"some": "thing"}))
    return tmp_path


def test_edge_export_omits_shortcuts(
    tmp_path: Path,
    capsys: pytest.CaptureFixture,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    profile_root = _make_minimal_profile(tmp_path)
    fake_policy = tmp_path / "policy" / "dotbrowser-pwa.json"
    _redirect_pwa(monkeypatch, edge_pwa, fake_policy)
    _seed_policy(fake_policy, ["https://app.element.io/"])

    args = argparse.Namespace(
        profile_root=profile_root,
        profile="Default",
        output=None,
    )
    edge_pkg.cmd_export(args)
    out = capsys.readouterr().out

    doc = tomllib.loads(out)
    # The header comment legitimately mentions `[shortcuts]` while
    # explaining what the export covers; the TOML body must not have
    # an actual shortcuts table.
    assert "shortcuts" not in doc
    assert doc["pwa"]["urls"] == ["https://app.element.io/"]


def test_chrome_export_omits_shortcuts(
    tmp_path: Path,
    capsys: pytest.CaptureFixture,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    profile_root = _make_minimal_profile(tmp_path)
    fake_policy = tmp_path / "policy" / "dotbrowser-pwa.json"
    _redirect_pwa(monkeypatch, chrome_pwa, fake_policy)
    _seed_policy(fake_policy, ["https://www.figma.com/"])

    args = argparse.Namespace(
        profile_root=profile_root,
        profile="Default",
        output=None,
    )
    chrome_pkg.cmd_export(args)
    out = capsys.readouterr().out

    doc = tomllib.loads(out)
    assert "shortcuts" not in doc
    assert doc["pwa"]["urls"] == ["https://www.figma.com/"]


# ---------------------------------------------------------------------------
# Vivaldi -- shortcuts (no defaults mirror, so emits all non-empty bindings)
# ---------------------------------------------------------------------------

def test_vivaldi_export_emits_non_empty_bindings(
    fake_vivaldi_profile_root: Path,
    tmp_path: Path,
    capsys: pytest.CaptureFixture,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Vivaldi has no defaults mirror.  Its export emits every command
    with a non-empty `shortcuts` field -- the closest approximation
    available -- and the export header documents that limitation."""
    fake_policy = tmp_path / "policy" / "dotbrowser-pwa.json"
    _redirect_pwa(monkeypatch, vivaldi_pwa, fake_policy)

    args = argparse.Namespace(
        profile_root=fake_vivaldi_profile_root,
        profile="Default",
        output=None,
        all_shortcuts=False,
    )
    vivaldi_pkg.cmd_export(args)
    out = capsys.readouterr().out

    doc = tomllib.loads(out)
    assert set(doc["shortcuts"]) == {
        "COMMAND_CLOSE_TAB",
        "COMMAND_NEW_TAB",
        "COMMAND_FOCUS_ADDRESSFIELD",
        "COMMAND_TAB_NEXT",
    }
    # PWA section emits even when empty (so the user sees the table exists).
    assert doc["pwa"]["urls"] == []


# ---------------------------------------------------------------------------
# CLI wiring smoke -- export subparser is registered
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("browser", ["brave", "vivaldi", "edge", "chrome"])
def test_export_subcommand_is_registered(browser: str) -> None:
    """`<browser> export --help` succeeds for every supported browser."""
    from dotbrowser.cli import build_parser
    parser = build_parser()
    # parse_args raises SystemExit on --help, so just check the parser
    # has an `export` action wired up.
    sub_actions = [
        a for a in parser._actions
        if isinstance(a, argparse._SubParsersAction)
    ]
    assert len(sub_actions) == 1
    browser_choices = sub_actions[0].choices
    assert browser in browser_choices
    browser_parser = browser_choices[browser]
    actions = [
        a for a in browser_parser._actions
        if isinstance(a, argparse._SubParsersAction)
    ]
    assert len(actions) == 1
    assert "export" in actions[0].choices
