#!/usr/bin/env python3
"""Regenerate src/dotbrowser/brave/command_ids.py from upstream headers.

Usage: python3 scripts/generate_brave_command_ids.py
Requires `gh` CLI authenticated.
"""
from __future__ import annotations

import base64
import json
import re
import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT = REPO_ROOT / "src" / "dotbrowser" / "brave" / "command_ids.py"

SOURCES = [
    ("chromium/chromium", "chrome/app/chrome_command_ids.h"),
    ("brave/brave-core", "app/brave_command_ids.h"),
]

DEFINE_RE = re.compile(r"^#define\s+(IDC_\w+)\s+(\d+)\s*(?://.*)?$")
SKIP_SUFFIXES = ("_START", "_END", "_FIRST", "_LAST", "_BOUNDARY")
SKIP_NAMES = {"IDC_MinimumLabelValue"}


def fetch(repo: str, path: str) -> str:
    raw = subprocess.check_output(
        ["gh", "api", f"repos/{repo}/contents/{path}", "--jq", ".content"]
    )
    return base64.b64decode(raw).decode()


def parse(text: str) -> dict[str, int]:
    out: dict[str, int] = {}
    for line in text.splitlines():
        m = DEFINE_RE.match(line.strip())
        if not m:
            continue
        name = m.group(1)
        if name in SKIP_NAMES or name.endswith(SKIP_SUFFIXES):
            continue
        out[name] = int(m.group(2))
    return out


def to_snake(idc: str) -> str:
    return idc.removeprefix("IDC_").lower()


def main() -> None:
    merged: dict[str, int] = {}
    for repo, path in SOURCES:
        merged.update(parse(fetch(repo, path)))

    name_to_id: dict[str, int] = {}
    seen_ids: dict[int, str] = {}
    for idc, cmd_id in merged.items():
        snake = to_snake(idc)
        if cmd_id in seen_ids and seen_ids[cmd_id] != snake:
            continue
        name_to_id[snake] = cmd_id
        seen_ids[cmd_id] = snake

    body = json.dumps(
        dict(sorted(name_to_id.items(), key=lambda kv: (kv[1], kv[0]))),
        indent=2,
    )
    OUT.write_text(
        '"""Auto-generated by scripts/generate_brave_command_ids.py. Do not edit by hand."""\n\n'
        f"NAME_TO_ID: dict[str, int] = {body}\n\n"
        "ID_TO_NAME: dict[int, str] = {v: k for k, v in NAME_TO_ID.items()}\n"
    )
    print(f"Wrote {OUT} ({len(name_to_id)} commands)")


if __name__ == "__main__":
    main()
